### ISSUE TITLE
Fix user guide to reflect parameter file 

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#65]
This part doesn't work anymore:

>> cut -f 1,2 --output-delimiter="  " output.dat | tail -n +2 > periods.dat
Now we can run plotypus as before, but instead of providing a period range, we will provide the periods file:
>> plotypus -i ogle-sample0 --periods periods.dat

**Comment by dwysocki** [comment]
This behavior has now been generalized by the `--parameters` flag. It's been a while, so I'll have to figure out how it works, and perhaps write a separate page to describe it.

It may be a good idea to start writing tutorial pages for individual flags, since each of them may have a lot of functionality behind them.

**Comment by dwysocki** [comment]
This has been absorbed into #78, and will be closed for redundancy.
