### ISSUE TITLE
Include option to output a residual file

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#66]
Prewhitening proceeds by fitting a curve, subtracting a fit, and then fitting the residuals. We can facilitate by including an option to output the residuals to a file.

**Comment by earlbellinger** [comment]
Should also output a residual plot

**Comment by dwysocki** [comment]
We should add the options `--output-table-residual` and `--output-plot-residual`.

Some questions:
- Should we have the table output in (phase, residual) or (time, residual) format?
- Should the plots essentially just be `plot_lightcurve()` called with residuals instead of magnitudes?
  If so, we may want to just repurpose that.

**Comment by earlbellinger** [comment]
table: (time, residual) 
plot: (phase, residual) 

and that's a possibility. I think we would probably want a dotted line at 0 though, so probably it'd be less convoluted to just separate them

**Comment by dwysocki** [comment]
Or we could maybe pull out some common functionality into a helper function.

**Comment by dwysocki** [comment]
This is now encompassed by #75, which deals with all of the new output formats.
