### ISSUE TITLE
Latexless

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#67]
Latex plots are great! But if the user doesn't have latex, we should render the plot without it.

**Comment by dwysocki** [comment]
This can be done by removing `text.usetex : True` from the `matplotlibrc` file.  We can do this in the one we provide in `src/plotypus/resources/matplotlibrc`, and still allow the user to pass in a custom one (with `text.usetex : True`) via the `--matplotlibrc` flag.

Of course, this could break things unexpectedly, so we need to test it. It might require a reinstall of the package, because we're modifying a resource file.

**Comment by dwysocki** [comment]
This has been fixed in #79.
